@url = http://localhost:3003/api/blogs
###

GET {{url}}

###
POST http://localhost:3003/api/blogs/
content-type: application/json

{
    "title": "How to code",
    "author": "Ayii",
    "url": "https://how-to-code",
    "likes": 3
}

###
PUT http://localhost:3003/api/blogs/60527b3d6edb1938b6cc3a78
content-type: application/json

{
    "likes": 5
}

###
DELETE http://localhost:3003/api/blogs/603a80082565080c5ecfb765

###
GET http://localhost:3003/api/users/


###
POST http://localhost:3003/api/users/
content-type: application/json

{
    "username": "Aishatuut",
    "password": "remi",
    "name":"Adeshewa Tolulope"
}
