@url = http://localhost:3003/api/blogs
###

GET {{url}}

###
POST http://localhost:3003/api/blogs/
content-type: application/json

{
    "title": "Hyyyyyyyyyy",
    "author": "Ayii",
    "url": "https://how-to-code",
    "likes": 3,
    "userid":"6057bee79572422a274d52d0"
}

###
PUT http://localhost:3003/api/blogs/60527b3d6edb1938b6cc3a78
content-type: application/json

{
    "likes": 5
}

###
DELETE http://localhost:3003/api/blogs/603a80082565080c5ecfb765

###
GET http://localhost:3003/api/users/


###
POST http://localhost:3003/api/users/
content-type: application/json

{
    "username": "Titilope",
    "password": "remi",
    "name":"Ajoke Ade"
}

###
POST http://localhost:3003/api/login/
content-type: application/json

{
    "username": "Titilope",
    "password": "remi"
}
###
POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IlRpdGlsb3BlIiwiaWQiOiI2MDVlMDgxNDNmY2Q3MjI2OGQ1OWVjNzkiLCJpYXQiOjE2MTY4ODQ5OTZ9.95h9mlFHvhxRzH_F3TC9ElTPLqPQIHgB-dBoaesO02I
{
    "title": "Hyyyyyyyyyy",
    "author": "Ayii",
    "url": "https://how-to-code",
    "likes": 3
}
